### ISSUE TITLE
Getting weather throws error

### ISSUE THREAD

**Issue by mikeyaworski** [trasigor/Sketchy-App-for-FitBit#3]
A few days ago, the following things happened:

- Clockface would only show loading symbol (hourglass) for weather
- When customizing settings for this clock in the FitBit app, it would just whitescreen
- After uninstalling and reinstalling the clock, I could adjust the settings, but again, it would whitescreen whenever I entered a location for the weather

**Comment by trasigor** [comment]
The issue 'caused by domain expire, which used for requests to backend.
